apiVersion: v1
kind: BuildConfig
metadata:
  name: TESTING
  labels:
    app: TESTING
    component: development
    logging-infra: development
    provider: openshift
spec:
  triggers:
    - type: ConfigChange
  runPolicy: Serial
  source:
    type: Binary
    binary: {}
  strategy:
    type: Docker
    dockerStrategy:
      from:
        kind: DockerImage
        name: dotnet/dotnet-20-runtime-rhel7
      dockerfilePath: Dockerfile
  output:
    to:
      kind: ImageStreamTag
      name: 'TESTING:latest'
  resources: {}
  postCommit: {}
  nodeSelector: null
status:
  lastVersion: 25
