apiVersion: v1
kind: Service
metadata:
  name: mssql
spec:
  selector:                  
    name: mssql
#  portalIP: 172.30.136.123   
  ports:
  - nodePort: 0
    port: 1433               
    protocol: TCP
    targetPort: 1433          
